### ISSUE TITLE
Adding gpmlogin

### ISSUE THREAD

**Issue by SkyYap** [TheGP/untidetect-tools#2]
Heard about [gpmlogin](https://gpmloginapp.com/) and was recommend by one of my friends. Didn't really try it. Was thinking to ask your opinion on the tools.

They claims they pass creepjs, fvision, pixelscan, browserleaks. Browserscan and iphey seems like not included in your Detection tests list too.

Hope can get your advice on this tools too.

**Comment by TheGP** [comment]
Just download it and test it yourself ;) I will do it later. I have added everything to my document, thanks, the tests are basically repeating the ones I already had, its just kinda basic ones.

Just make sure u will get core updates after purchasing it, because if not it may get expensive in the future.

The easiest way to test how u detected, try making some outlook email accounts till the step where u get a captcha then stop. After multiple attempts if u are detected u will get more captchas even if u create different browser identities.

**Comment by SkyYap** [comment]
> Just download it and test it yourself ;) I will do it later. I have added everything to my document, thanks! The tests repeat the ones I already had thou I think.
> 
> Just make sure u will get core updates after purchasing it, because if not it may get expensive in the future.
> 
> The easiest way to test how u detected, try making some outlook email accounts till the step where u get a captcha then stop. After multiple attempts if u are detected u will get more captchas even if u create different browser identities.

Thanks for sharing the ideas on how to get detected. Do I need to change my IP when testing it? Or I just need to keep create isolated VM on the system until I get detected.

**Comment by TheGP** [comment]
Need to change IP of course

**Comment by SkyYap** [comment]
> Need to change IP of course

Thanks a lot.
